# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

inhibit_all_warnings!

target 'MusicLounge' do
    pod 'CocoaSoundCloudAPI', :inhibit_warnings => true
    pod 'CocoaSoundCloudUI', :inhibit_warnings => true
    pod 'SDWebImage', '~>3.6'
    pod 'Parse'
    pod 'SVProgressHUD'
    pod 'DZNEmptyDataSet'
    pod 'DZNSegmentedControl', '~> 1.2'
    pod 'SWTableViewCell', '~> 0.3.7'
    pod "AFNetworking"
    pod 'MagicalRecord'
    pod "CSStickyHeaderFlowLayout"
    pod 'FreeStreamer'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ParseFacebookUtilsV4'
    pod 'FBSDKCoreKit'
    pod "TutorialKit"
end

target 'MusicLoungeTests' do

end

