# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

inhibit_all_warnings!

target 'MusicLounge' do
    pod 'CocoaSoundCloudAPI', :inhibit_warnings => true
    pod 'CocoaSoundCloudUI', :inhibit_warnings => true
    pod 'SDWebImage'
    pod 'Parse'
    pod 'SVProgressHUD'
    pod 'DZNEmptyDataSet'
    pod 'DZNSegmentedControl'
    pod 'SWTableViewCell'
    pod "AFNetworking"
    pod 'MagicalRecord'
    pod "CSStickyHeaderFlowLayout"
    pod 'FreeStreamer'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ParseFacebookUtilsV4'
    pod 'FBSDKCoreKit'
    pod 'SocketRocket'
    pod 'FormatterKit'
end

target 'MusicLoungeTests' do

end

